Timeouts
Islandora-Devops/isle-buildkit pull request #185
Opened 2022-02-08 20:57 UTC by dannylamb

Here is every possible timeout you might wanna set if you're running into weird errors with really really big files.  This won't change anything for existing installs, as all defaults are still the same.  But this way you can add them to your docker-compose.yml and play with them if you need it.

At born digital we've used this to get a couple of clients out of a bind with ingests of very large files.

2022-02-08 23:51 UTC, nigelgbanks requested changes
I've raised a pull request (https://github.com/Islandora-Devops/isle-buildkit/pull/188) against yours that moves all the configuration into `nginx.conf`  so its only managed in a single place. In reviewing your changes I've noticed that the reverse proxy for tomcat is no longer needed. Could you please review the other outstanding pull requests that are this repo?

2022-02-08 23:51 UTC, nigelgbanks commented on nginx/Dockerfile
> +    NGINX_LINGERING_TIMEOUT=60 \
The default is actual 5 seconds: https://nginx.org/en/docs/http/ngx_http_core_module.html#lingering_timeout

2022-02-08 23:51 UTC, nigelgbanks commented on nginx/Dockerfile
> +    PHP_REQUEST_TERMINATE_TIMEOUT=60 \
The default is `0` according to the documentation above for both of the `php` settings?

2022-02-08 23:51 UTC, nigelgbanks commented on nginx/Dockerfile
>      NGINX_KEEPALIVE_TIMEOUT=65 \
Just noticed this isn't the same as the default: https://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_timeout

2022-02-08 23:51 UTC, nigelgbanks commented on tomcat/Dockerfile
>      TOMCAT_ADMIN_NAME=admin \
`NGINX_WORKER_CONNECTIONS` and `NGINX_WORKER_PROCESSES` are not used.

2022-02-08 23:51 UTC, nigelgbanks commented on demo/Dockerfile
> +FROM ${repository}/drupal:${tag} AS drupal
This doesn't do anything as far as I can tell, not sure why it's included?

2022-03-03 18:14 UTC, merged

2022-03-03 18:24 UTC, dannylamb commented
Oh nice, thanks @nigelgbanks !  I have a follow up PR for this with an extra tomcat timeout I missed.

Also big thanks for getting rid of the extra reverse proxy layer!