Mariadb max_packet_allowed - Draft
Islandora-Devops/isle-buildkit pull request #295
Opened 2023-10-26 21:40 UTC by g7morris

Hi @nigelgbanks 

Trying to make max_packet_allowed a variable instead of a value not exposed to the user. 

Despite the `mariadb` container using the `base` image which I assumed uses confd, the environmental variable which I set in the isle-dc project `.env` file of `DB_MAX_ALLOWED_PACKET=268435456` doesn't seem to work. 

Am I missing something?

Just curious, I'll keep plugging along. 

Hope you are well. 

Cheers ,
Gavin

2023-10-27 14:12 UTC, g7morris commented
I think I see what is missing. I'm not accustomed to s6 overlay version 3 yet and can see I'm missing a chunk of definitions to fire. I'll work on filling in the missing bits. Ah learning. ;)

2023-10-27 15:39 UTC, g7morris commented
Okay a little progress on creating the S6 structure. 

I went ahead to at least give max_packet_allowed a default value of 256MB for when the container is first started (Dockerfile ENV) **however** confd & s6 don't seem to be "firing" or pulling the value from the project .env file. 

@nigelgbanks Any pointers on this per se?

2023-10-29 17:54 UTC, nigelgbanks commented
> the environmental variable which I set in the isle-dc project .env file of DB_MAX_ALLOWED_PACKET=268435456 doesn't seem to work.

That file is for docker-compose.yml file and is not included in the container environment variables. You'd have to specify the environment variable on the `mariadb` service here:

https://github.com/Islandora-Devops/isle-dc/blob/development/build/docker-compose/docker-compose.mariadb.yml#L11

For more information, the relevant docker-compose [documentation](https://docs.docker.com/compose/environment-variables/set-environment-variables/).

I'll submit a pull request that sorts this out and exposes it, following the conventions of the this repo.

2023-10-29 22:38 UTC, g7morris commented
Rather than making a new MR which ignores the work here, can you confirm what elements here are in the right direction please?

From your comments sounds like I just need to add the following below to the project `docker-compose.yml` as that was the missing part?

My intent isn't to make you redo my work here per se, just to learn and practice enough on how to expose variables properly.

```bash
  mariadb:
    image: ${REPOSITORY}/mariadb:${TAG}
    environment: 
      DB_MAX_ALLOWED_PACKET: ${DB_MAX_ALLOWED_PACKET:-268435456}
```

I'll test shortly. 

Thanks for taking a look!

2023-10-29 22:51 UTC, g7morris commented
Seems to work, the value in the mariadb-server.cnf file now reflects the value within the .env file when changed and if not uses the default 256MB. 

Are there other settings files or techniques needed?

2023-10-30 16:12 UTC, nigelgbanks commented
> Rather than making a new MR which ignores the work here, can you confirm what elements here are in the right direction please?

Sure, I was opting for a separate pull as every line will change, but I'll put notes on this pull.

2023-10-30 16:24 UTC, nigelgbanks requested changes
Also rebase on `main` to get passing tests as the latest version of `docker compose` introduced a breaking change, that has been fixed on `main`.

2023-10-30 16:24 UTC, nigelgbanks commented on mariadb/Dockerfile
> +ENV DB_MAX_ALLOWED_PACKET=268435456
Please change to the following, and remove the comment.

```bash
ENV MYSQL_MAX_ALLOWED_PACKET=16777216
```

Prefix to match the other environment variables provided by the image, see the [README.md](https://github.com/Islandora-Devops/isle-buildkit/tree/main/mariadb#database-settings).

Also, change the default value to be the same default as is provided by MariaDB (`16777216`) to not change the existing behavior. See the documentation [here](https://mariadb.com/docs/server/ref/mdb/system-variables/max_allowed_packet/).

2023-10-30 16:24 UTC, nigelgbanks commented on mariadb/rootfs/etc/confd/conf.d/mariadb-server.toml
> +src = "mariadb-server.tmpl"
Following convention, elsewhere in the repository the `src` should be named `mariadb-server.cnf.tmpl`.

Also rename the corresponding file in the template folder.

2023-10-30 16:24 UTC, nigelgbanks commented on mariadb/Dockerfile
> +ENV DB_MAX_ALLOWED_PACKET=268435456
Also add documentation for the new environment variable to the image's [README.md](https://github.com/Islandora-Devops/isle-buildkit/tree/main/mariadb#database-settings). 

For example:

| Environment Variable     | Default  | Description                                                                                                                                            |
| :----------------------- | :------- | :----------------------------------------------------------------------------------------------------------------------------------------------------- |
| MYSQL_ROOT_PASSWORD      |          | The database root user password. Defaults to `DB_ROOT_PASSWORD`                                                                                        |
| MYSQL_ROOT_USER          |          | The database root user (used to create the site database). Defaults to `DB_ROOT_USER`                                                                  |
| MYSQL_MAX_ALLOWED_PACKET | 16777216 | Max packet length to send to or receive from the server, [documentation](https://mariadb.com/docs/server/ref/mdb/system-variables/max_allowed_packet/) |

2023-10-30 16:24 UTC, nigelgbanks commented on mariadb/rootfs/etc/confd/conf.d/mariadb-server.toml
> +uid = 100
`uid` should be `0`

2023-10-30 16:24 UTC, nigelgbanks commented on mariadb/rootfs/etc/confd/conf.d/mariadb-server.toml
> +gid = 1000
`gid` should also be `0`.

2023-10-30 16:24 UTC, nigelgbanks commented on mariadb/rootfs/etc/confd/conf.d/mariadb-server.toml
> +mode = "0664"
`mode` should be `0644`.

2023-10-30 16:24 UTC, nigelgbanks commented on mariadb/rootfs/etc/confd/templates/mariadb-server.tmpl
> +max_allowed_packet ={{ getenv "DB_MAX_ALLOWED_PACKET" }}
Remove the comment as it is not accurate.

Change the line to:

```
max_allowed_packet={{ getenv "MYSQL_MAX_ALLOWED_PACKET" }}
```

Also don't forget to rename the file as is stated in an earlier comment.

2023-10-30 16:24 UTC, nigelgbanks commented on mariadb/rootfs/etc/s6-overlay/s6-rc.d/set-max-packet/type
> +oneshot
Delete this file.

2023-10-30 16:24 UTC, nigelgbanks commented on mariadb/rootfs/etc/s6-overlay/s6-rc.d/set-max-packet/up
> +/etc/s6-overlay/scripts/set-max-packet.sh
Delete this file.

2023-10-30 16:24 UTC, nigelgbanks commented on mariadb/rootfs/etc/s6-overlay/scripts/set-max-packet.sh
> +#!/command/with-contenv bash
Delete this file.

2023-10-30 16:24 UTC, nigelgbanks commented on mariadb/rootfs/etc/s6-overlay/s6-rc.d/set-max-packet/dependencies.d/ready
Delete this file.

2023-10-30 16:26 UTC, nigelgbanks commented
> From your comments sounds like I just need to add the following below to the project `docker-compose.yml` as that was the missing part?
> 
> My intent isn't to make you redo my work here per se, just to learn and practice enough on how to expose variables properly.
> 
> ```shell
>   mariadb:
>     image: ${REPOSITORY}/mariadb:${TAG}
>     environment: 
>       DB_MAX_ALLOWED_PACKET: ${DB_MAX_ALLOWED_PACKET:-268435456}
> ```
> 
> I'll test shortly.
> 
> Thanks for taking a look!

Yup, that was what I was saying.  👍

2023-10-30 19:01 UTC, nigelgbanks commented on mariadb/rootfs/etc/confd/conf.d/mariadb-server.toml
> +src = "mariadb-server.tmpl"
Oh, same goes for this `.toml` file, it should become `mariadb-server.cnf.toml`

2023-10-30 19:04 UTC, g7morris commented
Thanks for all the responses, comments and great insights here @nigelgbanks I'll get to work today with atomic fixes and commits, along with the appropriate resolutions. I appreciate you taking the time to help me learn and get the right changes in.

2023-10-30 20:34 UTC, g7morris commented
Hi @nigelgbanks 

Think we're ready for another review!

I've pushed all of the changes and here is a list below of what I did in order. 

Thanks again!

---

* Rebase done - https://github.com/Islandora-Devops/isle-buildkit/pull/295#pullrequestreview-1704568296
  * On branch - on local - `isle-buildkit git:(matomo-upgrade-4151)`
  * `git fetch origin`
  * `git rebase origin/main`
    * `Successfully rebased and updated refs/heads/mariadb_max_packet`
  * `git push origin HEAD --force`

```bash
Enumerating objects: 35, done.
Counting objects: 100% (35/35), done.
Delta compression using up to 8 threads
Compressing objects: 100% (20/20), done.
Writing objects: 100% (27/27), 2.93 KiB | 2.93 MiB/s, done.
Total 27 (delta 6), reused 2 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (6/6), completed with 4 local objects.
remote: 
remote: GitHub found 6 vulnerabilities on Islandora-Devops/isle-buildkit's default branch (6 moderate). To find out more, visit:
remote:      https://github.com/Islandora-Devops/isle-buildkit/security/dependabot
remote: 
To https://github.com/Islandora-Devops/isle-buildkit.git
 + c92f255...672b564 HEAD -> mariadb_max_packet (forced update)
```

* Dockerfile - https://github.com/Islandora-Devops/isle-buildkit/pull/295#discussion_r1376488638
  * DONE - variable name change along with ENV
  * DONE - README.md updated to reflect new default variable

* Confd - https://github.com/Islandora-Devops/isle-buildkit/pull/295#discussion_r1376491218
  * DONE - renamed confd tmpl & toml files according to project conventions
  * DONE - uid is now `0`
  * DONE - guid is now `0`
  * DONE - mode is now `0644`
  * DONE - comment is removed
  * DONE - variable is renamed to `MYSQL_MAX_ALLOWED_PACKET`

* S6 - 
  * DONE - removed `type` file
  * DONE - removed `up` file
  * DONE - removed script
  * DONE - removed `ready` file
  * DONE - removed `mariadb/rootfs/etc/s6-overlay/s6-rc.d/set-max-packet/dependencies.d/`
  * DONE - removed `mariadb/rootfs/etc/s6-overlay/s6-rc.d/set-max-packet`

2023-10-30 21:19 UTC, g7morris commented
Hi @nigelgbanks 

I think we're in business. 

Just tested all of this on a local isle-dc project and it seems to work nicely. 

FYI, one just can't exceed 1 GB as a max value per docs https://mariadb.com/docs/server/ref/mdb/system-variables/max_allowed_packet/. 

---

##### Test 1 - Use default settings of 16 MB

* Ran `make bake mariadb` for new `mariadb` Docker image

* Only one edit in`docker-compose.yml` to change the Docker image.

```bash
mariadb:
     image: islandora/mariadb:local
```

* `make up` - Start containers with new mariadb image
* `docker-compose exec mariadb bash` - shell into the container
* `mysql` - hop onto command line
* Ran this query `SHOW VARIABLES WHERE variable_name = 'max_allowed_packet';` and got the default value. 

```bash
MariaDB [(none)]> SHOW VARIABLES WHERE variable_name = 'max_allowed_packet';
+--------------------+----------+
| Variable_name      | Value    |
+--------------------+----------+
| max_allowed_packet | 16777216 |
+--------------------+----------+
1 row in set (0.004 sec)
```

---

##### Test 2 - Change settings in docker-compose.yml to 900 MB

* Ran `make bake mariadb` for new `mariadb` Docker image

* Edited in`docker-compose.yml` the following changes for the new Docker image and the new env. 

```bash
mariadb:
     image: islandora/mariadb:local
    environment:
        MYSQL_MAX_ALLOWED_PACKET: 943718400
```

* `make up` - Start containers with new mariadb image
* `docker-compose exec mariadb bash` - shell into the container
* `mysql` - hop onto command line
* Ran this query `SHOW VARIABLES WHERE variable_name = 'max_allowed_packet';` and got the newly updated value! 

```bash
MariaDB [(none)]> SHOW VARIABLES WHERE variable_name = 'max_allowed_packet';
+--------------------+----------+
| Variable_name      | Value    |
+--------------------+----------+
| max_allowed_packet | 943718400 |
+--------------------+----------+
1 row in set (0.004 sec)
```

Please note: That one can also use the following:

```bash
 mariadb:
    #image: ${REPOSITORY}/mariadb:${TAG}
    image: islandora/mariadb:local
    environment:
      MYSQL_MAX_ALLOWED_PACKET: ${MYSQL_MAX_ALLOWED_PACKET:-268435456}
```

with a line in the `.env` file `MYSQL_MAX_ALLOWED_PACKET=943718400 ` and this will work great as well.

2023-11-01 21:40 UTC, nigelgbanks approved these changes

2023-11-01 21:40 UTC, merged