Injecting DRUPAL_REVERSE_PROXY_IP for traefik if it's available
Islandora-Devops/isle-buildkit pull request #87
Opened 2020-11-19 19:14 UTC by dannylamb

I've managed to get the https situation sorted out a bit better, and this lets us properly configure drupal for a reverse proxy setup.  In order to make things work before it needed to be misconfgured on purpose, so this is a bit of an improvement :sweat_smile: 

If you're not using Traefik, you have to provide the IP(s) of the reverse proxy to Drupal via `DRUPAL_REVERSE_PROXY_IPS` using a comma separated list of IPs.  If you are using Traefik, it will try and auto-detect it generate the variable for you to save a step.

In order to actually set the settings, there's a new drush command, `islandora:settings:set-reverse-proxy`

You'll need this for an upcoming `isle-dc` PR and can test it with that.

2020-11-20 09:55 UTC, nigelgbanks commented
Not sure that this needs to be configurable via an environment variable, the requesting address is available as a global variable in `php`, for example in the following snippet, could be used instead:

```php
// Required when running Drupal behind a reverse proxy.
$settings['reverse_proxy'] = TRUE;
$settings['reverse_proxy_addresses'] = array($_SERVER['REMOTE_ADDR']);
$settings['reverse_proxy_trusted_headers'] = \Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_ALL;
```
As the address will be passed on via `nginx` from the request origin which may be `traefik` or an `alb` from AWS. Since the Drupal container itself would not be directly accessible from any other source other than the proxy I don't think using `$_SERVER['REMOTE_ADDR']` represents a security threat.

2020-11-20 13:32 UTC, nigelgbanks requested changes

2020-11-20 13:37 UTC, nigelgbanks commented
I've raised a pull request against your branch here: https://github.com/Islandora-Devops/isle-buildkit/pull/88 with what I think might work, testing will tell.

2020-11-20 14:03 UTC, nigelgbanks commented
The pull request I raised is not sufficient. It allows the variable to be set but a reasonable working default is still not possible.

2020-11-24 15:04 UTC, dannylamb commented
:bowing_man: I merged the execline, many thanks. Is there still something left for me to do here @nigelgbanks ?

2020-11-24 15:05 UTC, nigelgbanks approved these changes

2020-11-24 15:06 UTC, nigelgbanks commented
Good to go I think

2020-11-24 15:06 UTC, merged